##  ____                    _____ _             ___
##  / ___|  __ ___   _____  |_   _| |__   ___   / _ \ _   _  ___  ___ _ __
##  \___ \ / _` \ \ / / _ \   | | | '_ \ / _ \ | | | | | | |/ _ \/ _ \ '_ \
##   ___) | (_| |\ V /  __/   | | | | | |  __/ | |_| | |_| |  __/  __/ | | |
##  |____/ \__,_| \_/ \___|   |_| |_| |_|\___|  \__\_\\__,_|\___|\___|_| |_|
##


# Arena files are found in the map "Instances"
# Scoreboard can fully edited in the Scoreboard.yml file.
# Signs can be fully edited in the signs.yml files.